Repository Ojas-Arora/Ajivika, pull requests merged in 2025-01, with the labels that each got.

#22 #2 navbar fixed
  index.html
Labels: SWOC, INTERMEDIATE

#35 Added supabase authentication
  .vscode/settings.json
  index2.html
  login.html
  register.html
Labels: SWOC, ADVANCE

#41 #37 Top Scroll button Fixed
  index.html
Labels: SWOC, BEGINNER

#44 added FAQ section
  faq.html
  index.html
Labels: SWOC, INTERMEDIATE

#75 Fixed Issues in Responsiveness of landing page
  .hintrc
  index.html
  styles.css
Labels: SWOC, BEGINNER
